### PR TITLE
add Kalender.java

### PR DESCRIPTION
**Pull request by pratama404**

### CODE REVIEW

**Comment by pratama404** [comment]
why closed ?
i solve 3 pull can you help me ?

**Comment by GabrielStancu** [comment]
I accepted your PR and it was closed, it means it was successfully merged. You should see your progress in maximum 30 mins on the DigitalOcean page (your profile)

**Comment by pratama404** [comment]
Why you cancel my project please help i solve this

**Comment by pratama404** [comment]
yesterday it was already there and then back to the way it was, can you
check my pull request or maybe help me?

**Comment by GabrielStancu** [comment]
There's nothing I can check, it appears to be merged. If you are still facing the issue, please make as many PRs as you need to reach the 4 required PRs and I will gladly accept them, so that they will count towards your progress!

**Comment by pratama404** [comment]
i add kalender.java to your repository 
please check! 
and help me

**Comment by GabrielStancu** [comment]
It seems the repo was marked as spam and no PRs here were taken into consideration, I am sorry.

**Pull request merged**
